### PR TITLE
Fix incorrect output when using both > and >= (or similar) #12

### PR DESCRIPTION
**Pull request by hudochenkov**
Finally had found time to fix this the problem from #12 (it took exactly three months :sweat_smile:).

### CODE REVIEW

**Comment by hudochenkov** [comment]
Input:

```css
@media (1024px > width >= 768px) {}
@media (768px <= width < 1024px) {}

@media (1024px >= width > 768px) {}
@media (768px < width <= 1024px) {}

@media (1024px >= width >= 768px) {}
@media (768px <= width <= 1024px) {}
```

Output (v. 2.1.1):

```css
@media (min-width: 769px) and (max-width: 1024px) {}
@media (min-width: 768px) and (max-width: 1023px) {}

@media (min-width: 768px) and (max-width: 1023px) {}
@media (min-width: 769px) and (max-width: 1024px) {}

@media (min-width: 768px) and (max-width: 1024px) {}
@media (min-width: 768px) and (max-width: 1024px) {}
```

Output with this PR:

```css
@media (min-width: 768px) and (max-width: 1023px) {}
@media (min-width: 768px) and (max-width: 1023px) {}

@media (min-width: 769px) and (max-width: 1024px) {}
@media (min-width: 769px) and (max-width: 1024px) {}

@media (min-width: 768px) and (max-width: 1024px) {}
@media (min-width: 768px) and (max-width: 1024px) {}
```

**Comment by hudochenkov** [comment]
Ping.

**Comment by MoOx** [comment]
I have the right to merge but not to make a release on npm. @yisibl can you add me as a collab on npm? (`$ npm owner add moox`) :)

**Comment by MoOx** [comment]
ping @yisibl

**Comment by MoOx** [comment]
ping @yisibl

**Comment by yisibl** [comment]
I'm so sorry, it's been a long time. I'll be right away.

**Pull request merged**
